### ISSUE TITLE
Is there a way to iterate from end of bucket using forEach

### ISSUE THREAD

**Issue by cbrake** [timshannon/bolthold#107]
In our use case, we want to display the last X events from a large collection. This was working pretty well before we removed the Type index, but now it seems fairly slow -- I can't quite figure this out, so there may be something else going on.

We could also do this by time -- get events for the last 2 weeks if we could somehow do a seek to a particular time key.

We recently made this change:

![image](https://user-images.githubusercontent.com/402813/80253909-2c773a80-8648-11ea-8983-45cd1aca00d2.png)

Code is now:

```go
// Sample represents a value in time and should include data that may be
// graphed.
type Sample struct {
	// Type of sample (voltage, current, key, etc)
	Type string `json:"type,omitempty" influx:"type,tag"`

	// ID of the device that provided the sample
	ID string `json:"id,omitempty" influx:"id,tag"`

	// Average OR
	// Instantaneous analog or digital value of the sample.
	// 0 and 1 are used to represent digital values
	Value float64 `json:"value,omitempty" influx:"value"`

	// statistical values that may be calculated
	Min float64 `json:"min,omitempty" influx:"min"`
	Max float64 `json:"max,omitempty" influx:"max"`

	// Time the sample was taken
	Time time.Time `json:"time,omitempty" boltholdKey:"Time" gob:"-" influx:"time"`

	// Duration over which the sample was taken
	Duration time.Duration `json:"duration,omitempty" influx:"duration"`

	// Tags are additional attributes used to describe the sample
	// You might add things like friendly name, etc.
	Tags map[string]string `json:"tags,omitempty" influx:"-"`

	// Attributes are additional numerical values
	Attributes map[string]float64 `json:"attributes,omitempty" influx:"-"`
}

// ReadFaultHist reads the IS system fault history from the database
// Only iterates through database for x most recent faults. Set x to
// a negative integer to read all faults
func (db *IsDb) ReadFaultHist(x int) ([]data.Sample, error) {
	var faults []data.Sample
	query := bolthold.Where("Type").In(
		isdata.SampleTypeFaultFlowOff,
		isdata.SampleTypeFaultPresLow,
		isdata.SampleTypeFaultShutdown,
		isdata.SampleTypeFaultPresHigh,
		isdata.SampleTypeFaultNtFlowOff,
		isdata.SampleTypeFaultNtPresLow,
		isdata.SampleTypeFaultNtPresHigh).SortBy("Time").Reverse()

	errIterOverLimit := errors.New("Database iteration is greater than limit")

	count := 0
	err := db.store.ForEach(query, func(result *data.Sample) error {
		count++

		if x >= 0 && count > x {
			return errIterOverLimit
		}

		faults = append(faults, *result)

		return nil
	})

	if err != nil && err != errIterOverLimit {
		if err == bolthold.ErrNotFound {
			// data is not stored, so simply return nil array and nil error
			return nil, nil
		}

		// there was an error reading so return nil array and error
		return nil, err
	}

	return faults, nil
}
```

**Comment by cbrake** [comment]
Also, is it possible to do a Reverse() without a Where()?

**Comment by cbrake** [comment]
I think you've already answered this question once -- range query should do a Seek:

https://github.com/timshannon/bolthold/issues/62

Trying that now ...

**Comment by timshannon** [comment]
Full fledged databases with query planners are smart enough to iterate in the reverse order if then know it'll be quicker based on the statistics in a given index.  There is no query planner in Bolthold, it very simple does exactly what you ask and no more. 

You best best is always to limit the number of rows you are processing at any time, so I would suggest doing a where on time (the Key value), and then reversing it to get the last records.



```go
// all Records for the past two weeks
bh.Where(bh.Key).Gt(time.Now().AddDate(0, 0, -14).Reverse())
// or
bh.Where("Time").Gt(time.Now().AddDate(0, 0, -14).Reverse())
```

**Comment by cbrake** [comment]
the above is running pretty slow for a large data set -- so not sure if Seek should be that slow, or if there is something else going on. Can you point me to your code where the Find() does a bolt Seek() -- or maybe I'm misunderstanding how this works.

**Comment by timshannon** [comment]
Yeah, looks like I removed that code:

https://github.com/timshannon/bolthold/pull/70/commits/322df21f30086cf5efbbaff9d05f6dc0981e1ff4

I'll need to rethink how I was handling that before, and see if I can implement it in a safer way.

**Comment by cbrake** [comment]
OK, that makes sense then. I may try to drop down into bolt for this task for now and see if I can get what I need that way.

**Comment by cbrake** [comment]
thanks @timshannon -- my current time series code is raw boltdb, so can't quickly test -- however this is interesting, and I do need to do some time series work in the near future so will run some tests as soon as I can.

**Comment by timshannon** [comment]
Of course.  No rush, but be sure to let me know if you run into issues.

**Comment by timshannon** [comment]
I'm going to close this issue as there's been no response for over a year.  I assume it's been resolved.  Feel free to submit a new issues if you see issues.
