### ISSUE TITLE
his error occurs when fetching data from a specific bucket

### ISSUE THREAD

**Issue by king-wyx** [timshannon/bolthold#111]
his error occurs when fetching data from a specific bucket
![image](https://user-images.githubusercontent.com/20113166/81380296-3b2c1a00-913d-11ea-8c3d-3a5b955dc50c.png)
![image](https://user-images.githubusercontent.com/20113166/81380321-4a12cc80-913d-11ea-8e38-365b3169f1ec.png)

**Comment by timshannon** [comment]
`var bucket` is only valid inside your `Bolt().Update` func.

https://godoc.org/github.com/etcd-io/bbolt#Tx.Bucket

You can't reference it outside of that transaction.

**Comment by king-wyx** [comment]
but,i want get data,What i need to do

**Comment by timshannon** [comment]
You don't need to create the buckets manually.

Just insert your model:

```go
store, err := bolthold.Open(filename, 0666, nil)
if err != nil {
	//handle error
}
err = store.Insert("king", &modeluserModel{
	UserName:    "king",
	Password: "2959802013_",
})

dwedw := &model.UserModel{}
_ = store.Get("king", dwedw)
fmt.Println(dwedw)
```

**Comment by king-wyx** [comment]
When I have a default bucket, when I want to have a second bucket, should I innovate to create a store instance?

**Comment by timshannon** [comment]
I'm not exactly following what you mean, but if you want to manually create and manage buckets, then I wouldn't suggest using Bolthold.  Bolthold creates and manages it's own buckets based on the name of the type.

**Comment by king-wyx** [comment]
I have two types of data with different data structures, how to put them in the default bucket of Bolthold

**Comment by timshannon** [comment]
Bolthold automatically creates a bucket for each type you put in. Use a new type and you get a new bucket.

If you really need to store two different types in the same bucket you can use an anonymous struct and combine the two.

```go
struct {
  Type1
  Type2
}
```

**Comment by king-wyx** [comment]
This seems to be a good solution
