### ISSUE TITLE
Q: limit query without conditions

### ISSUE THREAD

**Issue by ivanjaros** [timshannon/bolthold#121]
I don't see any way to load results with pagination(ie. offset + limit) without starting a query with Where() which requires a field to apply a condition onto. Am I missing something here?

In other words I just want equivalent of `SELECT * FROM foo ORDER BY id ASC LIMIT 0,25`

**Comment by timshannon** [comment]
You can create an empty query that matches against everything the same way you create any empty object in Go.  The best place to find example queries is in the tests (https://github.com/timshannon/bolthold/blob/master/find_test.go#L402)

```Go
(&bolthold.Query{}).Skip(0).Limit(25).SortBy("ID")
```

**Comment by ivanjaros** [comment]
ok, i wasn't sure it would work. thanks.
