### ISSUE TITLE
Add support for batch inserts

### ISSUE THREAD

**Issue by ivanjaros** [timshannon/bolthold#124]
Since bolt has blocking transactions, it is often better to use batch writes instead of individual transactions. This increases performance quite a bit. My current use case is writing logs and since i do not want to block connections i simply use goroutines and from my previous experience bolt can handle about 250 writes per second. Since goroutines can just wait that is not a problem but with many requests there will be a ton of waiting/blocking/memory consuming goroutines waiting for exclusive write lock in bolt. So use of batches would **greatly** improve the performance.

**Comment by ivanjaros** [comment]
there is not much of a syntax difference.
```
func (s *Store) InsertBatch(key, data interface{}) error {
	return s.Bolt().Batch(func(tx *bolt.Tx) error {
		return s.insert(tx, key, data)
	})
}
```

the only thing with batches is to provide data that won't change inside the batch. when calling batch insert the user will know, from previous bolt experience, how to use it properly and it is of no concern for bolthold.

**Comment by timshannon** [comment]
Batch is just another form of creating a specific type of transaction.  You can already do batch inserts, and updates:

```go
err := store.Bolt().Batch(func(tx *bolt.Tx) error {
        return store.TxInsert(tx, key, data)
})

```
