### ISSUE TITLE
Distinct constraint

### ISSUE THREAD

**Issue by deiu** [timshannon/bolthold#125]
Hello,

Is there a way to specific a "Distinct" constraint when building a query? Basically something like SQL's SELECT DISTINCT.

Thanks!

**Comment by timshannon** [comment]
Aggregate queries are what you're looking for: https://github.com/timshannon/bolthold#aggregate-queries


Just like in SQL, running a distinct is the same as running a group by (for the most part.

You can find more examples in the tests: https://github.com/timshannon/bolthold/blob/master/aggregate_test.go

**Comment by deiu** [comment]
Thanks for the quick reply, I'll give it a try!
