### ISSUE TITLE
Aggregate query on nested struct

### ISSUE THREAD

**Issue by patbaker82** [timshannon/bolthold#130]
Very cool project.  I'm just spinning up on bolthold and I'm trying to figure out if this query is possible, or if I need to restructure my data.

I'm attempting to get a count of grouped Sentiment and I've tried bunch of things to no avail.  I think I'm trying to figure out if this is possible.  Frankly, I'm just spinning up on bolthold, so concede I'm likely not doing it right.
```
	type SentimentResult struct {
		File           string `json:"File"`
		Line           int    `json:"Line"`
		Sentiment      string `json:"Sentiment"`
		SentimentScore struct {
			Mixed    float64 `json:"Mixed"`
			Negative float64 `json:"Negative"`
			Neutral  float64 `json:"Neutral"`
			Positive float64 `json:"Positive"`
		} `json:"SentimentScore"`
	}

	type ProjectSentimentResult struct {
		ID              uint64 `boltholdKey:"ID"`
		ProjectId       string
		QuestionId      string
		JobId           string
		SentimentResult SentimentResult
	}
```

I've tried 

```
grp, err := store.FindAggregate(ProjectSentimentResult{}, bolthold.Where("JobId").Eq("ad1be007-91fa-41a5-5f48-b5720a107717"), "SentimentResult.Sentiment")
```

However that doesn't appear to work, because it complains about not knowing what SentimentResult.Sentiment is.  

`
The field SentimentResult.Sentiment does not exist in the type *main.ProjectSentimentResult"}
`

I can do an .Eq() assertion for the Sentiment value, but that would mean I would need to do N queries for the different values in Sentiment.

I thought about using a Find() query first with a matchfunc and subaggregate, but that will not return the counts as the resultant is stored in passed in result slice if I understand correctly.

Thanks in advance for any help!  I really appreciate it.

**Comment by timshannon** [comment]
Grouping currently doesn't support nested fields like queries do, otherwise this would work.

I'll mark this issue as an enhancement and add it when I get a chance.

Thanks for reporting this.

**Comment by timshannon** [comment]
This is fixed in master.

Thanks,
