### ISSUE TITLE
SliceIndex query ContainsAll not working

### ISSUE THREAD

**Issue by mmorrison57** [timshannon/bolthold#137]
Hello,

Recently I found an issue with querying using the ContainsAll criteria.

Using the unit tests provided in index_test.go I was able to confirm this by adjusting theTestSliceIndexWithPointers to the following. 

I updated the tests in 2 ways, first to not use Categories []*string but instead to Categories []string instead. Secondly, I updated the store.Find ContainsAll call to include both {cat1, cat2} (multiple items to search for, not just one). The test looks as follows and fails when it should succeed:

```go

func TestSliceIndexWithPointers(t *testing.T) {

	type Event struct {
		Id         uint64
		Type       string    boltholdIndex:"Type"
		Categories []string boltholdSliceIndex:"Categories"
	}

	testWrap(t, func(store *bh.Store, t *testing.T) {
		cat1 := "Cat 1"
		cat2 := "Cat 2"
		cat3 := "Cat 3"

		e1 := &Event{Id: 1, Type: "Type1", Categories: []string{cat1, cat2}}
		e2 := &Event{Id: 2, Type: "Type1", Categories: []string{cat3}}

		ok(t, store.Insert(e1.Id, e1))
		ok(t, store.Insert(e2.Id, e2))

		var es []*Event
		query := bh.Where("Categories").ContainsAll(cat1, cat2).Index("Categories")
		ok(t, store.Find(&es, query))
		equals(t, 1,len(es))
	})
}

```

The test expects the variable in e1 to be returned, but it is not found when run with an index. 

Remove the .Index("Categories") qualifier and it succeeds. 

```go
func TestSliceIndexWithPointers(t *testing.T) {

	type Event struct {
		Id         uint64
		Type       string    boltholdIndex:"Type"
		Categories []string boltholdSliceIndex:"Categories"
	}

	testWrap(t, func(store *bh.Store, t *testing.T) {
		cat1 := "Cat 1"
		cat2 := "Cat 2"
		cat3 := "Cat 3"

		e1 := &Event{Id: 1, Type: "Type1", Categories: []string{cat1, cat2}}
		e2 := &Event{Id: 2, Type: "Type1", Categories: []string{cat3}}

		ok(t, store.Insert(e1.Id, e1))
		ok(t, store.Insert(e2.Id, e2))

		var es []*Event
		query := bh.Where("Categories").ContainsAll(cat1, cat2)
		ok(t, store.Find(&es, query))
		equals(t, 1,len(es))
	})

}
```

**Comment by timshannon** [comment]
Thanks for the detailed issue and test repro.  I'll take a look.

**Comment by mmorrison57** [comment]
Absolutely. Sorry about the formatting issues! You may need to add back in the ` backticks in the event structs.

**Comment by timshannon** [comment]
I edited your comment to fix the formatting, FYI.

**Comment by timshannon** [comment]
Ok, there is definitely a logical inconsistency here with ContainsAll.

The slice indexes store the slice values individually, but ContainsAll needs to compare them as a group.

I just need to figure out the best way to handle it.  

The easiest option is to simply ignore the Index request in the query, like I do for "MatchFunc"queries where any value (like those not in the index) can be matched against, but that may not be the most performant.

**Comment by mmorrison57** [comment]
Thanks for confirming there is an issue there. I came to the same conclusion, ignore the index request and all is still working. Thank you

**Comment by timshannon** [comment]
Master branch should work for you now.
