### ISSUE TITLE
Sort by primary key has no effect seemingly 

### ISSUE THREAD

**Issue by sentriz** [timshannon/bolthold#139]
hi, thanks for the great library :ok_hand: 

i'm trying to sort by primary key, as in 

```go
type Row struct {
    ID uint64 `boltholdKey:"ID"`
}
```

and 

```go
var rows []*Row
db.Find(&rows, (&bolthold.Query{}).SortBy("ID").Reverse())
```

despite the .Reverse(), the `rows` will be sorted in ascending order 

full reproduction: https://go.dev/play/p/WVmNyeZODCK

thanks!

**Comment by timshannon** [comment]
Thanks for the report, definitely overlooked that since the PK is already sorted naturally, however it should absolutely handle reverse properly.

**Comment by timshannon** [comment]
Should be fixed now in master.  Thanks for reporting.

**Comment by sentriz** [comment]
thanks!
