### ISSUE TITLE
Two Structs, separated the db file or join in one file

### ISSUE THREAD

**Issue by goldalworming** [timshannon/bolthold#19]
I have two or more Structs, Should I separated the db file so I opened all file while init or join in one file?

type Item struct {
    ID       int64
    Name string `boltholdIndex:"Name"`
    Command string `boltholdIndex:"Command"`
    Created  int64
    Updated  int64
}
type Profile struct {
    ID       int64
    Name string `boltholdIndex:"Name"`
    Phone string `boltholdIndex:"Phone"`
    Created  int64
    Updated  int64
}

**Comment by timshannon** [comment]
So that kind of depend on how you want to manage your data files, but you can put both structs in one db file with no issues or overlap of any kind, and that's personally what I would recommend, as it's just simpler to manage.
