### ISSUE TITLE
struct tag to fill in key/id on results

### ISSUE THREAD

**Issue by lrstanley** [timshannon/bolthold#21]
First off, loving the library. Thank you! I noticed quickly however that when utilizing `Find()` (and similar methods), that the returned list has no identification of where it came from, or what it's origin key is. More specifically, if I use `Find()` to retrieve a list of matching values, I cannot determine what the original key is.

Reviewing query.go, it seems like this would be a fairly trivial addition, however what are your thoughts on this? For example, the simplest way one may add this is by filling in a matching struct tag.

```go
type SomeEntry struct {
	ID string `boltholdKey`
	// Could be interchangeable to byte as well, maybe? And, field name
	// shouldn't matter either.
	Key   byte `boltholdKey`
	Field value
}
```

When running the query, which loops through the boltdb key/values, it could fill in the ID field if it wasn't already specified after it was unmarshaled from gob.

There are only a few potential downsides if you could call them that, being:

- The amount of checks necessary to loop through the fields to see if the struct tag exists, but it's rare to ever see structs with a large amount of fields.
- When the struct is being saved, it would be stored in bolt as well, unless the end user also added a `gob:"-"` style tag. I don't think there is any way around this .
- Probably something else I missed. It's early in the morning for me, hah.

The only way I can see of getting around this is to store the key within the struct itself when it's being saved, but this seems non-idiomatic to me. This is what I am doing currently.

**Comment by timshannon** [comment]
Yeah, I can see how that's an issue. 

I like your idea, but I'm not a big fan of the hidden cost.  I'll benchmark and see if it's even something to worry about.

It's also non-obvious unless someone is paying close attention to the documentation, so I think I might add another option to just FindKeys, that just returns keys for a query.

Or maybe have the Find all return both an array of values and an array of keys, and if you don't want the keys, you just _ the value.  That seems pretty idiomatic for Go.

I'll throw together a few things, and see what works.

Thanks,

**Comment by lrstanley** [comment]
Implementing it on `Find()` and `FindKeys()` seems like an ok idea (and is also idiomatic), however that does mean that if users want to obtain the key (which I can see this coming up frequently), they would have to implement the boilerplate each time to insert it into their struct (it seems like I frequently see people putting the key/id into the returned struct by using a `ID` field, even when iterating over through bolt or things like database/sql implementations).

I have seen other libraries (primarily ORM), that use struct keys to do much of this kind of work. One example being gorm (maybe not the best library, or fastest either, though). Of course, I think the benchmarks will tell if it's a worthwhile add or not.

If it's very little overhead, maybe do both tag also support `FindKeys()`? Adding it onto `Find()` would break existing implementations -- is it worth doing so, to add to `Find()`?

**Comment by timshannon** [comment]
Could you take a look at the develop branch, and see if that works for you?  

I may also end up adding a FindKeys() function as well in that PR.

**Comment by lrstanley** [comment]
Looks good on my end. The written up documentation is straightforward as well.
