### ISSUE TITLE
Index ids using byteslice instead of gob

### ISSUE THREAD

**Issue by Xeoncross** [timshannon/bolthold#37]
Instead of using gob to marshal ids slices a [`[]byte` slice could be used directly](https://gist.github.com/Xeoncross/413c6fd7a181e51b775fc829a19cffb9).

**Comment by timshannon** [comment]
Possibly, although I'd be suprised if the Gob encoder isn't already taking that as a shortcut.

**Comment by timshannon** [comment]
So, correct me if I'm misunderstanding you. 

You basically want to flatten the Index Array of Byte Arrays:

``type keyList [][]byte``

To a single long byte array.

How do you reverse it?  How do you know how long each Key is in bytes?

**Comment by Xeoncross** [comment]
I was assuming each key was a 64bit integer. If that is true then [my tests show it would be significantly faster than using gob](https://github.com/Xeoncross/go-embeddable-stores/blob/master/cmd/experiments/byteindex/byteindex.go).

```
go test -bench=. --benchmem                                             
goos: darwin
goarch: amd64
pkg: github.com/Xeoncross/go-embeddable-stores/cmd/experiments/byteindex
BenchmarkByte-8   	    5000	    373481 ns/op	 1155563 B/op	      64 allocs/op
BenchmarkGob-8    	    2000	    609351 ns/op	 1055519 B/op	     228 allocs/op
PASS
ok  	github.com/Xeoncross/go-embeddable-stores/cmd/experiments/byteindex	3.199s
```

**Comment by timshannon** [comment]
A Key can be anything.  If you're using auto incrementing keys, then it will be a 64 bit integer, but it could be a string or a date or a struct or anything that uniquely identifies a row.

Thanks,

**Comment by Xeoncross** [comment]
Ah, I see that now: https://github.com/timshannon/bolthold/blob/master/store.go#L200

**Comment by Xeoncross** [comment]
I went ahead and saved what you had, plus `[]byte` marshaling into a repo in case it has any use to anyone. https://github.com/Xeoncross/keyset
