### ISSUE TITLE
coreos/bbolt code changes breaks bolthold

### ISSUE THREAD

**Issue by abbeydabiri** [timshannon/bolthold#38]
Hi Tim,

Great work you have done here,

There is an issue that occurs due to the recent code changes by the coreos/bbolt team.

The changes means the bolt reference is no longer correct and causes errors when building like below:

To fix it in my version i made a change like this:

**import (
bolt  "github.com/coreos/bbolt"
)**

The errors i encountered earlier are listed below:

 github.com/timshannon/bolthold
./aggregate.go:12:2: imported and not used: "github.com/coreos/bbolt"
./delete.go:10:2: imported and not used: "github.com/coreos/bbolt"
./get.go:10:2: imported and not used: "github.com/coreos/bbolt"
./index.go:12:2: imported and not used: "github.com/coreos/bbolt"
./put.go:11:2: imported and not used: "github.com/coreos/bbolt"
./query.go:15:2: imported and not used: "github.com/coreos/bbolt"
./store.go:12:2: imported and not used: "github.com/coreos/bbolt"
./store.go:17:6: undefined: bolt
./store.go:25:2: bolt is not a package

**Comment by Kvaz1r** [comment]
Their repo moved to another organization so now it should imported as : 
```
import (
bolt "go.etcd.io/bbolt"
)
```

**Comment by timshannon** [comment]
Thanks for the heads up.  I'll get the fix in sometime today.
