### ISSUE TITLE
Alternative key namespace designs

### ISSUE THREAD

**Issue by Xeoncross** [timshannon/bolthold#40]
Looking at the structure of the storage it seems an entire struct is encoded into one binary blob and saved by entity + id (along with any indexes). For example, taking [the simple example code here](https://github.com/timshannon/bolthold/issues/16) the resulting database is:

```
BUCKET "Person"
  KEY    "\n\f\x00\aHermann" = "*\xff\x81\x03\x01\x01\x06Person\x01\xff\x82\x00\x01\x02\x01\x04Name\x01\f\x00\x01\bDivision\x01\f\x00\x00\x00\x15\xff\x82\x01\aHermann\x01\atest123\x00"
BUCKET "_index:Person:Division"
  KEY    "\n\f\x00\atest123" = "\x15\xff\x83\x02\x01\x01\akeyList\x01\xff\x84\x00\x01\n\x00\x00\x10\xff\x84\x00\x01\v\n\f\x00\aHermann"
```

Looking at the [object storage](https://github.com/timshannon/bolthold/blob/master/put.go#L90) and hydration code it is clear that having all the fields in once place is easy to reason about. With indexes on every field used for lookup, you also can quickly search by value.

I'm curious if you ever thought about designing the layout to be more "flat" to help speed up range/prefix/sufix scans without requiring indexes on all search columns.

```
person:name:1 = Hermann
person:name:2 = Sam
person:division:1 = 31
person:division:2 = 23
etc...

b.Cursor().Seek('person:name:') ....
```

After searching the values of each key matching the prefix/range scan, one problem is knowing _before hand_ all the columns that exist on a given struct (including nested structs) so that you can reassemble the whole object. (That might require storing a copy of the struct for it's reflected field metadata on first save.)

A possible solution could be namespacing by ID instead of field. Assuming you could figure out how to split keys up to pull out names correctly (the split on ":" in this simple example isn't very safe). 

```
person:1:name = Hermann
person:1:division = 31
person:2:name = Sam
person:2:division = 23
etc...
```

**Comment by timshannon** [comment]
Maybe I'm not following what you're asking, but if you're talking about storing the main data in another format, you can always specify your own encoder.  The default is GOB simply for compatibility.

By far, the most expensive part of an entire query is the disk access.  Indexes help this by providing short cuts to the specific data being looked for, so that not as much disk needs to be access.

There are a lot of different encoding formats you could use that would be much faster than GOB, but it doesn't amount to much compared to the cost of looking up the data on disk, which you'd always have to do.

**Comment by Xeoncross** [comment]
The encoder assumes the object / data struct is stored in a single format of some sort: GOB, protobuff, BSON, JSON, etc...

I was talking about splitting up the data by struct-fields/map-keys into unique key-value pairs for storage separate from each other. In the current system, the whole `Person` struct (and all struct-fields) are stored under a single database key.

So instead of 

```
BUCKET "Person"
  KEY    "{id}" = {GOB_STRUCT}
```

Something more like

```
BUCKET "Person"
  KEY  "{id}:Name" = "Hermann" 
  KEY "{id}:Division" = "*test123"
```

**Comment by timshannon** [comment]
So in a struct with 5 fields we'd have to read 5 keys to get the entire struct, meaning even more disk reads?

Or are you saying, in addition to storing the whole object, we also store each field separately, almost like an index that is only good for that specific value?

Either way it sounds like way more reads to grab all the data.

**Comment by timshannon** [comment]
What you're getting to is basically what cockroach labs did (https://www.cockroachlabs.com/blog/sql-in-cockroachdb-mapping-table-data-to-key-value-storage/).

And that makes a lot of sense for something like SQL where you aren't necessarily consuming the entire object.  You have a language to specific that you only want specific data.

For some workloads, and when you need to join data, and do all of the complicated scenarios that you can do with SQL, it makes sense.  And maybe you could redesign the query API to allow you to select out individual fields, in which case this could be a win.  However, if your workload requires that level of granular control, I'm betting you'd be better served in many ways by using SQLite.

**Comment by Xeoncross** [comment]
Yes, cockroachdb, TiDB, and others are good examples of _one key, one property_. However, there are other use cases for bolthold users where this would make sense, such as situations where the current query indexes are too large to fit into memory resulting in the requirement to download, decode, and scan each struct in a giant map-reduce query.

Having each field stored separately, would allow prefix, suffix, and range queries without needing to iterate over (basically) the entire dataset for that object.

That said, I don't think support for queries for individual fields is a compelling reason to make any changes to bolthold right now. I just wanted to raise the question and dialog about it.
