### ISSUE TITLE
nested structs and find

### ISSUE THREAD

**Issue by ftKnox** [timshannon/bolthold#43]
There seems to be an issue with nested structs that are pointers, example of breaking code here https://play.golang.org/p/0LWo8-91p2Z

I have applied the following patch to query.go and it seems to be working. I am not very familiar with the reflect package, so I am unsure if this is the best way to fix.

```diff
--- query.go	2019-03-14 14:15:46.000000000 -0600
+++ ../query.fix.go	2019-03-14 14:17:04.000000000 -0600
@@ -778,11 +778,7 @@
 		func(r *record) error {
 			var rowValue reflect.Value
 
-			if elType.Kind() == reflect.Ptr {
-				rowValue = r.value
-			} else {
-				rowValue = r.value.Elem()
-			}
+			rowValue = r.value.Elem()
 
 			if keyType != nil {
 				err := decode(r.key, rowValue.FieldByName(keyField).Addr().Interface())
@@ -791,7 +787,11 @@
 				}
 			}
 
-			sliceVal = reflect.Append(sliceVal, rowValue)
+			if elType.Kind() == reflect.Ptr {
+				sliceVal = reflect.Append(sliceVal, rowValue.Addr())
+			} else {
+				sliceVal = reflect.Append(sliceVal, rowValue)
+			}
 
 			return nil
 		})
```

**Comment by timshannon** [comment]
Thanks, I'll write up some tests and take a look.

**Comment by timshannon** [comment]
Definitely able to replicate the issue.

Thanks, for providing a specific scenario for testing.

**Comment by ftKnox** [comment]
You're welcome. Thanks for your work on this!

**Comment by timshannon** [comment]
This should be good now.

Thanks,

**Comment by ftKnox** [comment]
confirmed, thanks!
