### ISSUE TITLE
Instead of using the entire refelct library consider using a version of the library with the debugging features removed

### ISSUE THREAD

**Issue by wade-welles** [timshannon/bolthold#45]
I was considering using this or the badger version of your library but you use the reflect library which a decent portion is debugging code. However there are "lite" versions of this library that have much of that cut out. There is a good chance you can find a version of the library with the pieces you need for your aggregate functionality without having the unsafe stuff included. 

Just a consideration, feel free to close this if you disagree.

**Comment by timshannon** [comment]
It looks like there's an internal lib for this: https://github.com/golang/go/tree/master/src/internal/reflectlite

But it's internal so I can't use it.
