### ISSUE TITLE
how to use string array in a query with [where In]  ?

### ISSUE THREAD

**Issue by ystyle** [timshannon/bolthold#46]
```go
var ids []string
where := bolthold.Where("Id").In(ids...) //It's error
```

**Comment by timshannon** [comment]
Unfortunately, the `In` function necessarily need to accept a slice of empty interface and you are passing in an array of strings.

So you can do this:

```go
where := bolthold.Where("Id").In("1", "2", "3")
```
And each individual value passed in satisfies the empty interface.  But when you pass in the slice as a whole,  the whole slice of type string is not the same type as a slice of empty interfaces.  You need to copy your slice into another slice of empty interfaces:

```go
t := []string{"1", "2", "3", "4"}
s := make([]interface{}, len(t))
for i, v := range t {
    s[i] = v
}
where := bolthold.Where("Id").In(s...)
```

**Comment by ystyle** [comment]
Thank you

**Comment by timshannon** [comment]
You can now use the helper func `bolthold.Slice`

```Go
var ids []string
where := bolthold.Where("Id").In(bolthold.Slice(ids)...)
```
