### ISSUE TITLE
no query.NotIn(...interface{}) ?

### ISSUE THREAD

**Issue by mh-cbon** [timshannon/bolthold#48]
hi,

i cant find the `NotIn` verb in the query implementation. Am i missing something obvious ?

**Comment by timshannon** [comment]
Currently there isn't one.  You could accomplish the same with with a `MatchFunc` query:

```go
bolthold.Where("Name").MatchFunc(func(ra *bolthold.RecordAccess) (bool, error) {
			field := ra.Field()
			val, ok := field.(string)
			if !ok {
				return false, fmt.Errorf("Field not a string, it's a %T!", field)
			}

			return val != "one" && val != "two" && val != "three"
		}),
```

**Comment by mh-cbon** [comment]
Don t you think it deserves to be part of the standard querier API ?

**Comment by timshannon** [comment]
Not necessarily, no.  I'd prefer to have a more general `Not` modifier that could be applied to any query criterion rather than have one single negative logic critierion that be accomplished with MatchFunc.

**Comment by timshannon** [comment]
You can now do `Not().In("one", "two", "three")` type of queries with https://github.com/timshannon/bolthold/pull/52
