### ISSUE TITLE
consider query.Like() ?

### ISSUE THREAD

**Issue by mh-cbon** [timshannon/bolthold#50]
Hi,

Have you considered a `Like(thresholdComuter, threshold)` criterion that would be able to filter items given a threshold of resemblance ? 

Where resemblance could be a Levenshtein distance, or something more complex. 

(I m trying to figure out how i will handle search text, for the bigger picture)

**Comment by timshannon** [comment]
I would assume people are more familiar with Regex than with Levenshtein distance thresholds.  You can accomplish the same thing as a normal database like (plus more) with the Regexp criterion.  But if you really need this you can use MatchFunc.
