### ISSUE TITLE
consider Find(<*T>) as well as Find(<*[]T>)

### ISSUE THREAD

**Issue by mh-cbon** [timshannon/bolthold#54]
Hi,

can you also consider to improve Find so it can also handle structs ?

It would return an error if the input was a struct and that no rows were found, unlike a slice input.

right now i work around with something like this

```go

func (m ModelAware) FindOne(out interface{}, q *bolthold.Query) error {
	rslice := reflect.New(reflect.SliceOf(reflect.TypeOf(out).Elem()))
	slice := rslice.Interface()
	err := m.Store.Find(slice, q.Limit(1))
	if err != nil {
		return err
	}
	if rslice.Len() < 1 {
		return notFound(out)
	}
	reflect.ValueOf(out).Set(rslice.Elem().Index(0))
	return nil
}
```

I suspect it generates few useless allocations.

**Comment by timshannon** [comment]
I would prefer to add a separate `FindOne` method rather than overload the existing `Find` method.

This also is in line with standard library's sql package:

[DB.Query](https://golang.org/pkg/database/sql/#DB.Query) vs [DB.QueryRow](https://golang.org/pkg/database/sql/#DB.QueryRow)
