### ISSUE TITLE
bolthold.Key

### ISSUE THREAD

**Issue by mh-cbon** [timshannon/bolthold#65]
hi,

 what is the thing around `bolthold.Key` ? few times i hit difficulties and wonders because i used the raw field name instead of this special key.

Is it possible to makes this totally optional ?

**Comment by mh-cbon** [comment]
Another stupid question. The ID field is defined as an uint64. but uint64 is not so great because it does not allow to distinguish an object with zero ID and an object with a zero value. said more clearly i find it difficult to identify an object exiting in the database from an object that does not exists at all in the database.

Is it something you might consider ?

**Comment by timshannon** [comment]
> what is the thing around bolthold.Key ? few times i hit difficulties and wonders because i used the raw field name instead of this special key.

Bolthold is built on the BoltDB **Key-Value** store.  It uses one byte slice (the **Key**) to refer to another byte slice (the **Value**).

When you store a Go struct in Bolthold, it serializes the struct into the **Value** and allows you to run queries against that value by automatically deserializing and comparing the fields in that struct.  The **Key** is a completely different value and can be anything you want, but the key allows you to go directly to a record without having to read off of disk, deserialize the **Value** and compare fields to find it.  Grabbing a record by the **Key** will always be quicker than any query.

To grab a record by **Key** you can call `bolthold.Get`, but sometimes it can be useful to run a query again the key values so the `bolthold.Key` const allows you to say "Apply this critiera *not* to any field in the **Value** but to the value of the **Key**".

> Is it possible to makes this totally optional ?

It is completely optional, and only used in queries.  If you mean can you optionally not have a **Key** in your Key-Value store?  No.  There needs to be something there.  If you don't care what the value of the key is, feel free to use `bolthold.NextSequence()` and forget about it.

> ... The ID field is defined as an uint64. but uint64 is not so great because it does not allow to distinguish an object with zero ID and an object with a zero value. said more clearly i find it difficult to identify an object exiting in the database from an object that does not exists at all in the database.

You can use ***anything*** as your key.  You don't need to use `uint64`.  If you want to use an int64, go for it.  If you want to use a struct, you can do that as well.  Bolthold will take any Go object you pass in and serialize it into the **Key**'s value.

The only defining characteristic of the **Key** is that it should uniquely identify whatever data you are storing in that record.
