### ISSUE TITLE
criterion value might not be in database during seekCursor

### ISSUE THREAD

**Issue by timshannon** [timshannon/bolthold#67]
See #66

**Comment by confiks** [comment]
In addition to the example in the PR, doesn't the code at https://github.com/timshannon/bolthold/blob/e52bb1c/index.go#L295 forget to check if the criterion is actually a `bolthold.Key`?

**Comment by timshannon** [comment]
It could be clearer, but that seekCursor func is only used by iterators, that ONLY operate on key criteria.
