### ISSUE TITLE
best practices using boltholdKey tag

### ISSUE THREAD

**Issue by cbrake** [timshannon/bolthold#69]
Hi, I'm using bolthold to store time series samples, so using time.Time as key. As the sample type includes a Time field, I have the boltholdKey tag on that field.

Is there any way to keep the data from being stored in the Value struct as well as the key? Is a gob:"-" tag recommended on all fields that have the boltholdKey tag?

**Comment by timshannon** [comment]
The gob tag isn't necessary.  You could keep the key value from being stored with the struct by not including it in your struct or emptying the value before you store it.
