### ISSUE TITLE
Does bolthold support 'Batch read-write transactions'?

### ISSUE THREAD

**Issue by jaehue** [timshannon/bolthold#7]
I want to use `bolthold` package for BoltDB.
I think it is very useful for me. 
But it seems that we cannot use batch read-write transaction(https://github.com/boltdb/bolt#batch-read-write-transactions) in `bolthold` package.
Could you explain how to use batch tx in `bolthold` package?

**Comment by timshannon** [comment]
Each bolthold CRUD operation comes with an alternate call that lets you specify your own transaction.  Those functions all start with Tx

So if you wanted to do batch updates you could use the [TxUpdateMatching](https://godoc.org/github.com/timshannon/bolthold#Store.TxUpdateMatching) func

```Go
err := db.Batch(func(tx *bolt.Tx) error {
    store.TxUpdateMatching(tx, &DataType{}, bolthold.Where("fieldname").Eq(value), func(record interface{}) error {
      ...
	return nil
    })
    return nil
})
```

**Comment by jaehue** [comment]
Great!
I'm trying use `TxUpdateMatching` method.
👍
