### ISSUE TITLE
best practice for reading large amounts of data

### ISSUE THREAD

**Issue by cbrake** [timshannon/bolthold#73]
What is the best way to read a large amount of data from a database (say 20,000 records) without reading everything into one result array? Is there any type of cursor functionality?

**Comment by timshannon** [comment]
Currently there is no cursors at the BoltHold level, but Bolt itself supports cursors, and getting it directly from the source is one option.
https://godoc.org/github.com/timshannon/bolthold#Store.Bolt

You could have cursor-like functionality by using the MatchFunc query.

```go
bolthold.Where("Name").MatchFunc(func(ra *bolthold.RecordAccess) (bool, error) {
			// if record matches my criteria call func to process on this record
                       // always return false so values don't get added into memory of matching records
		}),
```

I could see adding a `ForEach` method that runs a query for each matching record of a query.  It would basically do the same thing as the above.

**Comment by timshannon** [comment]
Added https://github.com/timshannon/bolthold/issues/74 to track adding a forEach method.

It should be possible, but there may be some complications with Or's and skips.  We'll see.

**Comment by timshannon** [comment]
You can now use `ForEach` for this:

```Go
err := store.ForEach(boltholdWhere("Id").Gt(4), func(record *Item) error {
	// do stuff with record

	// if you return an error, then the query will stop iterating through records

	return nil
})
```

**Comment by cbrake** [comment]
nice!  thanks for implementing this, I look forward to trying it.
