### ISSUE TITLE
installation issues in dependency

### ISSUE THREAD

**Issue by slotheroo** [timshannon/bolthold#78]
go get is failing because of problems with the go.etcd.io/bbolt package.

See https://github.com/etcd-io/bbolt/issues/195

**Comment by timshannon** [comment]
Thanks for the heads up.  Not sure what to do at this point though.

**Comment by slotheroo** [comment]
Sure thing. It's just meant as an alert for you and anyone else using bolthold.

One easy workaround is to remove the extension from the bolt_unix_aix.go file in etcd-io/bbolt. (i.e. rename it to bolt_unix_aix)

**Comment by leobeosab** [comment]
Heads up I made a fix for this hopefully it gets merged soon 
[#198](https://github.com/etcd-io/bbolt/pull/198)
