### ISSUE TITLE
Exported function store.IndexExists requires unexported argument type bucketSource

### ISSUE THREAD

**Issue by freakinhippie** [timshannon/bolthold#79]
I'm attempting to use bolthold and when I tried to test if an index is available using the store.IndexExists() function I came across this issue. I'm pretty new to golang so maybe I'm missing something but I think the interface type definition in _store.go_ should be exported.

**Comment by timshannon** [comment]
Yep, you're absolutely right.  I'll fix it up.

Thanks,

**Comment by timshannon** [comment]
Grabbing the latest from master should have BucketSource exported.

Let me know if you run into any issues.

Thanks,
