### ISSUE TITLE
Indexes for lists

### ISSUE THREAD

**Issue by n1try** [timshannon/bolthold#82]
Hi, I'm quite new to `bbolt`, `bolthold` and using key-value stores in general. I'd like to know whether it is possible to create an index for every value in a list. Let me give an example.

```
type Item struct {
    Id int
    Name string
    Categories []string
}
```

Given this struct, I'd like to be able to efficiently get all `Item`s for a given category, i.e. I want an index like `{ "category 1": [15, 27], "category 2": [3, 9, 25] }`, where the numbers correspond to `Item.Id`s.

How could I achieve this?

**Comment by Kvaz1r** [comment]
Efficiently would be make all operations in single traverse with ForEach: 

```
package main

import (
	"fmt"
	"log"

	"github.com/timshannon/bolthold"
)

type Item struct {
	Id         int
	Categories []string
}

func main() {
	store, err := bolthold.Open("test.db", 0666, nil)
	if err != nil {
		log.Fatal(err)
	}
	store.Insert(15, &Item{
		Id:         15,
		Categories: []string{"cat 1", "cat 2"},
	})
	store.Insert(20, &Item{
		Id:         20,
		Categories: []string{"cat 3", "cat 1"},
	})
	store.Insert(25, &Item{
		Id:         25,
		Categories: []string{"cat 2", "cat 4"},
	})
	cat := map[string][]int{}
	store.ForEach(&bolthold.Query{}, func(record *Item) error {
		for _, k := range record.Categories {
			_, ok := cat[k]
			if !ok {
				cat[k] = []int{record.Id}
			} else {
				cat[k] = append(cat[k], record.Id)
			}
		}
		return nil
	})
	fmt.Println(cat)
}
```

I didn't write handling possible errors in example above for every operations because too lazy :)

**Comment by n1try** [comment]
Thanks, but that's not exactly what I was looking for. I want the index to be persistent in `bbolt` and managed by `boltholt`. What you suggested is more like a temporary, custom-build, in-memory cache.

**Comment by timshannon** [comment]
So you can create an index on a list of items, but it's not going to do what you expect.  Consider the following records:

| ID 	| Name 		| Categories 		|
| --- 	| --- 		| --- 				|
| 1 	| John 		| red, green, blue 	|
| 2 	| Bill 		| red, purple	 	|
| 3 	| Jane 		| red, orange	 	|
| 4 	| Brian		| red, purple	 	|


You may expect your `Categories` index to look like the following:

| Categories 	| ID 			| 
| --- 			| --- 			| 
| red			| 1, 2, 3, 4	| 
| green			| 1 			|
| blue			| 1 			|
| purple		| 2, 4 			|
| orange		| 3 			|

But they'll actually look like this:

| Categories 		| ID 			| 
| --- 				| --- 			| 
| red, green, blue	| 1				| 
| red, purple		| 2, 4 			|
| red, orange		| 3 			|


So if you did a query like this:
```Go
bh.Where("Categories").Contains("red").Index("Categories")
```

It'll work, but you'll be reading more records than you'd expect.  You'd only "save reads" on values where the list of categories exactly match.

The current behavior [appears to match](https://stackoverflow.com/questions/4058731/can-postgresql-index-array-columns) what Postgres does with arrays, and I think, if we'd want to support indexing individual items in slices individually we'd want to have a separate index type that is an explicitly used, such as with a separate struct tag.  Either that, or use an optional interface that you could implement to explicitly determine how any type is indexed.

**Comment by n1try** [comment]
Thanks for the detailed answer, very cool! Essentially, what I'm trying to replicate here is an index for a join table in a many-to-many relation (speaking in RDMS terminology). Looks like right now there is no way to achieve that using `bolthold`. What I still could do is manually create an index bucket directly on the `bolt.Db` instance. But I would manually have to keep it consistent all the time, which is going to be pain.

The Readme mentions that 

> you can implement the Storer interface, to specify your own indexes

Could this potentially help me? And do you have an example on how to use `Storer`? The API docs alone didn't really help me.

Also, do you plan to implement one of your two suggested solutions some time in the future?

**Comment by timshannon** [comment]
If you're trying to do a join, then I would recommend de-normalizing the data, just like you'd want to do in Postgres or any other RDMS.

It could be I'm missing specifics because the example we're using is so simple, but if you are wanting to join two different sets of records, they should be stored separately.

There are no joins in BoltHold, so you'd need to do the join manually, by looping through both record types, regardless.

I'll leave this issue open until I implement sliced indexed, or define a clearer issue separately.

Thanks,

**Comment by n1try** [comment]
Actually "join" was the wrong word. In the simplest case I really just need sliced indexes, so **+1 for that feature** 😊

**Comment by tsal** [comment]
Regarding the edit - I think this might be the better route; create a type alias for the `string` slice, then implement the Storer interface, but I'm just now looking at bolthold for the first time today, so the best I can do is offer the anonymous implementation within the library that uses `reflect`:

https://github.com/timshannon/bolthold/blob/master/store.go#L143

and

https://github.com/timshannon/bolthold/blob/master/store.go#L161

the hardest part seems like maybe looping through your slice and generating an `Index` func for each slice index; the rest is be implementing the Storer interface, which if I understand correctly, bolthold will just use if defined.

I'm thinking there's probably more effort to this than it looks on the surface, but I'm going to need a similar structure, so I'll find out in the next few days!
