### ISSUE TITLE
ContainsAny not working with slice index?

### ISSUE THREAD

**Issue by n1try** [timshannon/bolthold#87]
Take the example code from [this issue](https://github.com/timshannon/bolthold/issues/85#issue-567852461), but replace `Contains()` with `ContainsAny()` for the two queries.

Output is:
```
[1]
0xc000087be0 (*string) cannot be compared with <nil> (<nil>)
[]
```

Doesn't look correct to me.

**Comment by timshannon** [comment]
Fixed in master.  Thanks.
