### ISSUE TITLE
Indexing not working when embedded struct is nil

### ISSUE THREAD

**Issue by ftKnox** [timshannon/bolthold#98]
So I think we are getting close to finally getting this figured :). Indexes weren't working correctly and I had to add this patch to fix (it passes go test as well). Also have you thought about changing this to support multi-depth embedded structs via an inline recursion function or similar?

```diff
diff --git a/store.go b/store.go
index 0915944..aa94f19 100644
--- a/store.go
+++ b/store.go
@@ -230,13 +230,14 @@ func (s *Store) newStorer(dataType interface{}) Storer {
                                                anonType := anonValue.Type()
                                                if anonType.Kind() == reflect.Ptr {
                                                        if anonValue.IsNil() {
-                                                               return nil, nil
+                                                               if tpType.Field(i).Name == name {
+                                                                       return nil, nil
+                                                               }
                                                        }
                                                        anonType = anonType.Elem()
                                                }
                                                for j := 0; j < anonType.NumField(); j++ {
                                                        if anonType.Field(j).Name == name {
-
                                                                return s.encode(anonValue.Interface())
                                                        }
                                                }
@@ -246,7 +247,7 @@ func (s *Store) newStorer(dataType interface{}) Storer {
                                                }
                                        }
                                }
-                               panic("Field " + name + " does not exist in this value")
+                               panic("Field \"" + name + "\" does not exist in this value")
                        }
                }
                if strings.Contains(string(field.Tag), BoltholdSliceIndexTag) {
```

**Comment by timshannon** [comment]
As soon as you start supporting indexing recursively, things get very very complicated.  How do you handle linked-list like structures that point to themselves?  You'd create infinite loops try to recurse them.  When you have an index on a field that is part of slice of values that is part of a parent struct, what is the index actually pointing to?

I'm all for properly supporting anonymous structs, because they basically act like top level struct fields, but the data model doesn't really make sense for nested structures.

**Comment by timshannon** [comment]
Can you send me specifically what type of struct you're using?  I'm not convinced your changes are fixing what you think they are, or else I'm misunderstanding the issue.

The tests have this struct:

```go
type (
		Profile struct {
			Username string `boltholdIndex:"Username" json:"username"`
			Password string `json:"password"`
		}

		User struct {
			*Profile

			ID   string
			Name string
		}
	)
```

The index is on `Username`, but the name of the anonymous struct is `Profile`.  The issue fixed in the last patch was due to the fact that `Profile` (a pointer) was nil, and so we couldn't get the value of `Username` from a nil pointer parent.

Your patch checks to see if the index name matches the name of the anonymous struct, which would mean you're trying to put an index on the anonymous struct?  What am I missing?

**Comment by ftKnox** [comment]
yep put 2 anonymous structs in there

```go
type (
		Profile struct {
			Username string `boltholdIndex:"Username" json:"username"`
			Password string `json:"password"`
		}
                Account struct {
			GuardianName string `boltholdIndex:"GuardianName" json:"name"`
			Create time.Time `json:"created"`
                }

		User struct {
			*Profile
                        *Account

			ID   string
			Name string
		}
	)
```

The GuardianName field in *Account wont return any value when attempting to build the index for it. The code sees that it exists, but then hits that return nil,nil and returns an empty string for the index value.

**Comment by timshannon** [comment]
Ah, that makes more sense.  I've got enough to work off of now.  It is dropping out early when it shouldn't.

Thanks,

**Comment by ftKnox** [comment]
The nesting of anonymous structs is nice, since it allows you to keep potentially empty data from being saved into bolt. But I use structs like this quite often and it has only been recently that I have had enough data to care about indexing it. Sometimes this data is coming out of a foreign api that  for various reasons, I can't control or change the data structures. But, I may still need indexing on nested values. In any case, this library has been super helpful and I appreciate your efforts on it.

```go
type (
	User struct {
		*Address
		*Account
		*History

		ID   string `boltholdKey:"ID" json:"id"`
		Team *Team  `json:"team"`
	}

	Customer struct {
		*Address
		*Account
		*History

		ID string `boltholdKey:"ID" json:"id"`
	}

        //this would likely be its own db, but also be used above in the user account,
       //to just store the id, etc. Upon a rest api call allows you to rehydrate into 
       //a complete structure nested in the user account
	Team struct {
		*History

		ID   string `boltholdKey:"ID" json:"id"`
		Name string `json:"name"` //name given by user to this team
	}

	History struct {
		Created  time.Time `json:"created,omitempty"`
		Modified time.Time `json:"modified,omitempty"`
	}

	Address struct {
		Name     string `boltholdIndex:"Name" json:"name"` //name given by user to this team
		Address1 string `json:"address1"`
		Address2 string `json:"address2"`
		City     string `json:"city"`
		State    string `json:"state"`
		ZipCode  string `json:"zipcode"`
		Phone    string `boltholdIndex:"Phone" json:"phone"`
		Email    string `boltholdIndex:"Email" json:"email"`
	}

	Account struct {
		*Credentials

		IsActive  bool      `json:"is_active"`
		Hidden    bool      `json:"hidden"`
		Disabled  bool      `json:"disabled"`
		LastLogin time.Time `json:"last_login,omitempty"`
	}

	Credentials struct {
		Username string `boltholdIndex:"Username" json:"username,omitempty"`
		Password string `json:"password,omitempty"`
	}
)
```

**Comment by timshannon** [comment]
Ah, I see.  Not Nested Structs, but Nested Anonymous structs.   Yeah, I'll see what I can do.  We'll still have a infinite recursion issue, but I think Gob encoding has the same issue.

**Comment by ftKnox** [comment]
Yes sorry, nested anonymous structs. I agree, but really, I think that comes down to developer skill and understanding. Libraries that have too many safety nets become limiting for developing edge cases, which for some reason, I seem to deal with a lot. 

There is also another edge case like below when promoted field name matches one in the primary struct. So which one do you choose when reflecting through the struct? Seems like maybe the index bucket names should be keyed like Address.Name when using anon structs. As for use case, I may have one database full of just addresses. I want to keep the user db as light and clean as possible. So using anonymous structs allows a lot of flexibility in how I choose to store the user record. If I have a bunch of users without addresses, I am not storing a bunch of empty keys into the db and wasting space and speed. If I haven't mentioned it, I am using json as my encoder/decoder when saving into bolt.

```go

type (
	User struct {
		*Address

		ID   string `boltholdKey:"ID" json:"id"`
		Name string `boltholdIndex:"Name" json:"name"` //name given by user to this team
	}

	Address struct {
		ID       string `boltholdKey:"ID" json:"id"`
		Name     string `boltholdIndex:"Name" json:"name"` //name given by user to this team
		Address1 string `json:"address1,omitempty"`
		Address2 string `json:"address2,omitempty"`
		City     string `json:"city,omitempty"`
		State    string `json:"state,omitempty"`
		ZipCode  string `json:"zipcode,omitempty"`
		Phone    string `boltholdIndex:"Phone" json:"phone, omitempty"`
		Email    string `boltholdIndex:"Email" json:"email, omitempty"`
	}
)
	addressID := uuid.Must(uuid.NewV4()).String()

	user := &User{
		ID:   uuid.Must(uuid.NewV4()).String(),
		Name: "Test User",
		Address: &Address{
			ID: addressID,
		},
	}

	address := &Address{
		ID:       addressID,
		Name:     "work",
		Address1: "123 Test Street",
		Address2: "Suite 123",
		City:     "Somewhere",
		State:    "CA",
		ZipCode:  "12345",
		Phone:    "123-123-1234",
		Email:    ".@.",
	}

	addressDB.Insert(addressID, address)
	userDB.Insert(user.ID, user)
```

**Comment by timshannon** [comment]
Yeah I actually found an issue where I was using the field name as the index name.  The index should instead be named after the Struct tag, so you can name them whatever you want to make sure they are separate indexes.

**Comment by ftKnox** [comment]
You can name them that, but you can't use them as an index.

```go

// Index specifies the index to use when running this query
func (q *Query) Index(indexName string) *Query {
	if strings.Contains(indexName, ".") {
		// NOTE: I may reconsider this in the future
		panic("Nested indexes are not supported.  Only top level structures can be indexed")
	}
	q.index = indexName
	return q
}
```

**Comment by ftKnox** [comment]
but yes i get that i could name "User_Address" or whatever, but i did run into that above.

**Comment by ftKnox** [comment]
> Yeah I actually found an issue where I was using the field name as the index name. The index should instead be named after the Struct tag, so you can name them whatever you want to make sure they are separate indexes.

sorry i read over that too fast, i thought you were referencing my User.Address suggestion above.

**Comment by ftKnox** [comment]
but in reality, though you wouldn't want to change the index from "Name" in the address struct, cause when querying that db specifically you wouldn't want to do dbAddress.Find(&address, bolthold.Where("User_Address").Eq("whatever").

**Comment by timshannon** [comment]
Querying and and indexing is different.

Querying will work with nested structs using the `.` notation.  Indexes will indexes *should* index by whatever name you  put in the tag:

`dbAddress.Find(&address, bolthold.Where("Address.Name").Eq("whatever").Index("Address_Name")

**Comment by timshannon** [comment]
Also I'll remove that panic, so if you want to name your index with a `.` you can.  That was leftover when index names were hardcoded by field name.

**Comment by ftKnox** [comment]
does this still apply with anonymous structs? cause you don't need Address.Name in the where since the field(s) are promoted to the parent struct

**Comment by timshannon** [comment]
I don't have tests for all of those scenarios yet, but it *should* work just like it does in Go, where you don't need to specify the anonymous struct name unless you have a namespace conflict on the anonymous field.

`Address.Name` vs `User.Name`

**Comment by timshannon** [comment]
Give master a try.  I rewrote how all of the anonymous structs are handled, and added some better tests.

Thanks for opening issues, and testing all of this.  It exposed some bugs I didn't know I had in there.

**Comment by ftKnox** [comment]
Ok, sounds great. I will let you know if I bump into anything. Thanks!
